### ISSUE TITLE
Connecting to Sentinel hub with a proxy

### ISSUE THREAD

**Issue by cnette** [sentinel-hub/sentinelhub-qgis-plugin#38]
I can not connect the plugin to the service due to a proxy. I try "default" proxy and "httpproxy" as settings.
![image](https://github.com/sentinel-hub/sentinelhub-qgis-plugin/assets/150814501/7c165fde-a9fb-4d96-9987-0befa6d50130)

It could be due to urllib to ping the website and could be resolve by QgsNetworkAcessManager like in the [documentation to publish plugins](https://plugins.qgis.org/publish/) :
Plugins should make use of QgsNetworkAccessManager instead of using urllib2/requests/etc... which often fail to use correct proxy settings.

2023-11-14T09:44:15     WARNING    Traceback (most recent call last):
              File "C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
              conn = connection.create_connection(
              File "C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
              raise err
              File "C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
              sock.connect(sa)
             ConnectionRefusedError: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
              httplib_response = self._make_request(
              File "C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
              self._validate_conn(conn)
              File "C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\urllib3\connectionpool.py", line 978, in _validate_conn
              conn.connect()
              File "C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\urllib3\connection.py", line 309, in connect
              conn = self._new_conn()
              File "C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
              raise NewConnectionError(
             urllib3.exceptions.NewConnectionError: : Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\requests\adapters.py", line 439, in send
              resp = conn.urlopen(
              File "C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
              retries = retries.increment(
              File "C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\urllib3\util\retry.py", line 446, in increment
              raise MaxRetryError(_pool, url, error or ResponseError(cause))
             urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='identity.dataspace.copernicus.eu', port=443): Max retries exceeded with url: /auth/realms/CDSE/protocol/openid-connect/token (Caused by NewConnectionError(': Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))

**Comment by Adrok24** [comment]
Hi, could you send a capture of the settings you are using? Could you tell which kind of proxy you are using?

**Comment by cnette** [comment]
Hi, 
This is default config and I try also this configuration HTTP or HTTPS
![image](https://github.com/sentinel-hub/sentinelhub-qgis-plugin/assets/150814501/08426a2f-419d-44c9-9cf7-95559139d052)

![image](https://github.com/sentinel-hub/sentinelhub-qgis-plugin/assets/150814501/e7d52f46-45e5-4b2f-b73e-cf11d69d8573)

**Comment by Adrok24** [comment]
The proxy settings are saved and taken from a qsettings file. This file is a .config or .ini that can be found in a hidden folder in windows for example C:\Users\<YourUsername>\AppData\Roaming\QGIS\QGIS3\profiles\default\QGIS\QGIS3.ini. Could you search for 'proxy' in this file and tell me if your configurations are stored there?

**Comment by cnette** [comment]
Hello, 
This is my proxy settings : 

QgsOptionsBase\grpProxy\collapsed=false 
Search "proxy" (14 hits in 1 file of 1 searched) 
C:\Users\xxxx\AppData\Roaming\QGIS\QGIS3\profiles\default\QGIS\QGIS3.ini (14 hits) 
Line 85: QgsOptionsBase\grpProxy\collapsed=false 
Line 548: plugin_installer\seen_plugins=db_manager, MetaSearch, processing, latlontools, quick_map_services, QuickWKT, MemoryLayerSaver, simplesvg, valuetool, GeoCoding, GroupStats, timemanager, menu_from_project, Hotlink, GarminCustomMap, loadthemall, RemoveEmptyLayers, mask, dimensioning, lizmap, MultiEdit, profiletool, midvatten, qNote, mmqgis, wfsclient, plugin_reloader, quicksaveqml, osmpoly_export, pgversion, inasafe, qgsAzimuth, qgiscloud, qgSurf, DirectionalSlope, pstimeseries, VectorFieldCalc, pointsamplingtool, numericalDigitize, contour, LecoS, crayfish, pdokservicesplugin, Cxf_in, flowTrace, qtiles, sextante_animove, geospatialsimulation, plaingeometryeditor, tmsforkorea, kuw_filter, SemiAutomaticClassificationPlugin, splitmultipart, DistroMap, shapefile_encoding_fixer, zoomrc, qProf, BulkVectorExport, DataDrivenInputMask, ContrastHomogenizer, ZoomToPostcode, DigitizingTools, nominatim, LandXml, qchainage, VoGisProfilTool, send2google_earth, BufferByPercentage, pgRoutingLayer, htpgeoprocessor, cadastre, geopunt4Qgis, shp_to_obs, PPConverter_20, Qgis2threejs, Video_UAV_Tracker, realcentroid, b4udignl2, ViewshedAnalysis, joinmultiplelines, lrs, spline, SLD4raster, opeNoise, go2streetview, attributePainter, StreetView, Vgi2ShpConverter, EasyCustomLabeling, AreaAlongVector, clickfu, postgisQueryBuilder, IDECanarias, StreamFeatureExtractor, VectorBender, interlis, SGDiagramDownloader, autoSaver, zoomtopaste, SVG2ColoR, clipper, ConstraintChecker, PointConnector, MapsPrinter, QuickOSM, alkisplugin, ArcheoCAD, DissolveWithStats, svir, NNJoin, SwapVectorDirection, AzimuthDistanceCalculator, temporalprofiletool, pickLayer, MultipleLayerSelection, QgsWcpsClient1, VectorMCDA, ProfileFromPoints, TomBio, networks, processing_workflow, MBTiles2img, ClipToHemisphere, Redistricting, concavehull, survey_design, scpplugin, MultiDistanceBuffer, FeatureGridCreator, OSTranslatorII, postgis_geoprocessing, instantprint, ntv2_transformations, tiss, DsgTools, catalogotf_plugin, beePen, OSMDownloader, LineDirectionHist ... 
Line 807: networkAndProxy\networkTimeout=60000 
Line 813: networkAndProxy\userAgent=Mozilla/5.0 
Line 1373: [proxy] 
Line 1375: proxyEnabled=true 
Line 1376: proxyHost=proxy.shom.fr 
Line 1376: proxyHost=proxy.shom.fr 
Line 1377: proxyPort=3128 
Line 1378: proxyUser= 
Line 1379: proxyPassword= 
Line 1380: proxyType=DefaultProxy 
Line 1380: proxyType=DefaultProxy 
Line 1381: ***@***.***() 




De: "Adrián Di Paolo" ***@***.***> 
À: "sentinel-hub/sentinelhub-qgis-plugin" ***@***.***> 
Cc: "Camille Netter" ***@***.***>, "Author" ***@***.***> 
Envoyé: Mercredi 6 Décembre 2023 22:40:56 
Objet: Re: [sentinel-hub/sentinelhub-qgis-plugin] Connecting to Sentinel hub with a proxy (Issue #38) 





The proxy settings are saved and taken from a qsettings file. This file is a .config or .ini that can be found in a hidden folder in windows for example C:\Users<YourUsername>\AppData\Roaming\QGIS\QGIS3\profiles\default\QGIS\QGIS3.ini. Could you search for 'proxy' in this file and tell me if your configurations are stored there?

**Comment by Adrok24** [comment]
Hi, thank you for reporting this. We are trying to replicate this issue to find a solution. Once we find a fix for this we are going to reach you back.

**Comment by cnette** [comment]
Hello, 
I'd like to ask you again about this. 
Have you found a solution to my plugin problem?
